#ifndef APP_EW2023_CARDASHBOARD_H_
#define APP_EW2023_CARDASHBOARD_H_

#include "platform.h"

// Path to UI assets Folder
#if defined(MSVC_PLATFORM) || defined(BT8XXEMU_PLATFORM)
#define TEST_DIR                            "..\\..\\..\\Sdcard\\"
#else
#define TEST_DIR                            "/"
#endif

#define GET_CALIBRATION                     0

//#define SERIAL_ENABLE 1
//#define SERIAL_EMU_ENABLE 1
#define SERIAL_REPLAY_ENABLE 1

#define GPIO_PUSHBUTTON    (10)
#define RP2040_GPIO_PUSHBUTTON (27)
#define GPIO_PUSHBUTTON_FUNC  (pad_gpio10)
#if defined(RP2040_PLATFORM)
#define READ_PUSH_BUTTON gpio_get(RP2040_GPIO_PUSHBUTTON)
#elif defined(FT9XX_PLATFORM)
#define READ_PUSH_BUTTON gpio_read(GPIO_PUSHBUTTON)
#endif
#if defined(BT81X_ENABLE)
#define LOAD_PICTURE_FROM_FLASH_ENABLE (1)	/* Enable to use images from flash */
#define LOAD_BITMAP_FLASH_TO_RAM (1) /* Load bitmap from flash to RAM_G to speed up the display performance */
#endif

/* These Definitions are auto-generated by excel in EW2018_Dashboard_Plan.xlsx */
#define ADDR_FONT_EHSMB_26 (4096UL) /* GUI_1_01_FONT_EHSMB_26.glyph */
#define ADDR_FONT_EHSMB_26_INDEX (69120UL) /* GUI_1_02_FONT_EHSMB_26.xfont */
#define ADDR_FONT_SUIGI_32 (69312UL) /* GUI_1_03_FONT_SUIGI___32.glyph */
#define ADDR_FONT_SUIGI_32_INDEX (80384UL) /* GUI_1_04_FONT_SUIGI___32.xfont */
#define ADDR_GUI_1_BACKGROUND (80512UL) /* GUI_1_05_Background.raw */
#define ADDR_GUI_1_NEEDLE (442112UL) /* GUI_1_06_Needle.raw */


#define ADDR_GUI_2_BACKGROUND (529728UL) /* GUI_2_01_Background2.raw */
#define ADDR_GUI_2_NEEDLE (849728UL) /* GUI_2_02_Needle.raw */
#define ADDR_GUI_2_FUEL (888192UL) /* GUI_2_03_nFuel.raw */
#define ADDR_GUI_2_TEMP (940032UL) /* GUI_2_04_nTemp.raw */
#define ADDR_GUI_2_TURNARROW (991872UL) /* GUI_2_05_TurnArrow.raw */


#define ADDR_GUI_3_BACKGROUND (992128UL) /* GUI_3_01_Background.raw */
#define ADDR_GUI_3_FOREGROUND (1410240UL) /* GUI_3_02_Foreground.raw */
#define ADDR_GUI_3_GEAR (1625408UL) /* GUI_3_03_Gear.raw */
#define ADDR_GUI_3_HIGHLIGHT_FG (1632576UL) /* GUI_3_04_HighLightFg.raw */
#define ADDR_GUI_3_HIGHLIGHT_BG (1633920UL) /* GUI_3_05_HightLightBg.raw */
#define ADDR_GUI_3_NEEDLE1 (1636032UL) /* GUI_3_06_Needle1.raw */
#define ADDR_GUI_3_NEEDLE2 (1653504UL) /* GUI_3_07_Needle2.raw */
#define ADDR_GUI_3_NEEDLE3 (1713088UL) /* GUI_3_08_Needle3.raw */
#define ADDR_GUI_3_BACKGROUND_INDEX (1730560UL) /* GUI_3_09_Background_index.raw */
#define ADDR_GUI_3_BACKGROUND_LUT (2147648UL) /* GUI_3_10_Background_lut.raw */



#define SIZE_GUI_1 (449216UL)
#define SIZE_GUI_2 (462400UL)

//#define USE_PALETTED8 (1)
#ifdef USE_PALETTED8
	#define SIZE_GUI_3 (738432UL - 418112UL)
#else
	#define SIZE_GUI_3 (738432UL)
#endif



#define RAM_FONT_ADDR		(RAM_G_SIZE - 1024)

#define GET_RAM_ADDRESS(BASE_ADDR, ITEM_ADDR)  (ITEM_ADDR - BASE_ADDR)

typedef enum {
	SCREEN_INIT = 0,
	SCREEN_MAIN,
	NUM_OF_SCREEN
}Screen_Status_t;

typedef enum {
	DIR_STRAIGHT = 0,
	DIR_LEFT,
	DIR_RIGHT,
	DIR_BACK,
	NUM_OF_DIRECTION
}Direction_t;


//SimHub struct should be:
//  speed;rpm;feul*10;temp;pos;lap;gear;curLap;
//ex: P165;3000;652;
typedef struct {
	int speed;
	int rpm;
	int feul;
	int temp;
	char pos[2] ;  // = "1";
	char lap[2] ; // = "0";
	char gear[4] ; //  = "N";
	char curLap[10] ; //  = "00:00.000";
}CarInfo;

typedef struct
{
	Screen_Status_t screen_status;
	float speed;/* 0 - 180*/
	float rpm; /* 0 - 600 */
	uint16_t temperature; /* 0-100% */
	uint16_t fuel; /* 0-100% */
	uchar8_t gear; /* R N 1 2 3 4 5 */
	uint8_t picIndex;/* 1-2 */
	Direction_t direction;
}SystemStatus_t;

typedef struct Image_header
{
	uint16_t Format;
	int16_t Width;
	int16_t Height;
	int16_t Stride;
	uint32_t Arrayoffset;
}Image_header_t;


/* These definition set the first item address of each GUI */
#define ADDR_GUI_1   ADDR_GUI_1_BACKGROUND
#define ADDR_GUI_2   ADDR_GUI_2_BACKGROUND

#define NUM_BACKGROUND (2)

enum IMAGE_INDEX {
	IMAGE_GUI_1_BACKGROUND =0,
	IMAGE_GUI_1_GEAR_BOX,
	IMAGE_GUI_1_NEEDLE,


	IMAGE_GUI_2_BACKGROUND_LEFTHALF,
	IMAGE_GUI_2_BACKGROUND_RIGHTHALF,
	IMAGE_GUI_2_NEEDLE,
};

// GUI 1 handle lists
#define HANDLE_GUI_1_BACKGROUND  (0)
#define HANDLE_GUI_1_GERA_BOX    (1)
#define HANDLE_GUI_1_NEEDLE      (2)


// GUI 2 handle lists
#define HANDLE_GUI_2_BACKGROUND_LEFTHALF   (0)
#define HANDLE_GUI_2_BACKGROUND_RIGHTHALF  (1)
#define HANDLE_GUI_2_NEEDLE      (2)

#define TAG_BUTTON  (200)

#define DEACCELARATION(target, prev, rate) 				\
do {								\
    target = (prev) + (rate) * ((target) - (prev));	\
    prev = (target);						\
} while (0)

#endif /* APP_EW2023_CARDASHBOARD_H_ */
