_cout=1
tag_none                   = _cout ; _cout = _cout + 1
tag_                       = _cout ; _cout = _cout + 1
tag_bg                     = _cout ; _cout = _cout + 1
tag_datetime               = _cout ; _cout = _cout + 1
tag_air_flow1_front        = _cout ; _cout = _cout + 1
tag_air_flow2_front        = _cout ; _cout = _cout + 1
tag_air_flow3_front        = _cout ; _cout = _cout + 1
tag_air_flow1_rear         = _cout ; _cout = _cout + 1
tag_air_flow2_rear         = _cout ; _cout = _cout + 1
tag_air_flow3_rear         = _cout ; _cout = _cout + 1
tag_air_flow1_passenger    = _cout ; _cout = _cout + 1
tag_air_flow2_passenger    = _cout ; _cout = _cout + 1
tag_air_flow3_passenger    = _cout ; _cout = _cout + 1
tag_onoff                  = _cout ; _cout = _cout + 1
tag_front                  = _cout ; _cout = _cout + 1
tag_rear                   = _cout ; _cout = _cout + 1
tag_ac                     = _cout ; _cout = _cout + 1
tag_air                    = _cout ; _cout = _cout + 1
tag_fan_driver             = _cout ; _cout = _cout + 1
tag_fan_passenger          = _cout ; _cout = _cout + 1
tag_sync                   = _cout ; _cout = _cout + 1
tag_auto                   = _cout ; _cout = _cout + 1
tag_c                      = _cout ; _cout = _cout + 1
tag_f                      = _cout ; _cout = _cout + 1
tag_temp_incr_driver       = _cout ; _cout = _cout + 1
tag_temp_incr_passenger    = _cout ; _cout = _cout + 1
tag_temp_incr_rear         = _cout ; _cout = _cout + 1
tag_temp_decr_driver       = _cout ; _cout = _cout + 1
tag_temp_decr_passenger    = _cout ; _cout = _cout + 1
tag_temp_decr_rear         = _cout ; _cout = _cout + 1
tag_fan_decrease_driver    = _cout ; _cout = _cout + 1
tag_fan_decrease_passenger = _cout ; _cout = _cout + 1
tag_fan_decrease_rear      = _cout ; _cout = _cout + 1
tag_fan_increase_driver    = _cout ; _cout = _cout + 1
tag_fan_increase_passenger = _cout ; _cout = _cout + 1
tag_fan_increase_rear      = _cout ; _cout = _cout + 1
tag_fan_driver             = _cout ; _cout = _cout + 1
tag_fan_passenger          = _cout ; _cout = _cout + 1
tag_fan_rear               = _cout ; _cout = _cout + 1
tag_loop                   = _cout ; _cout = _cout + 1 # use in a loop
